# Generated by Django 3.2.18 on 2023-04-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
