# Generated by Django 3.2.18 on 2023-07-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0006_alter_booking_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Rainbow Burgers', 'Rainbow Burgers'), ('No chicken Burgers', 'No chicken Burgers'), ('No chicken', 'No chicken'), ('Wraps', 'Wraps'), ('Wraps Dressings', 'Wraps Dressings'), ('Accessories', 'Accessories'), ('Desserts', 'Desserts'), ('Dip', 'Dip'), ('Drinks', 'Drinks'), ('Add-ons', 'Add-ons'), ('Snacks', 'Snacks')], max_length=30)),
                ('description', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
