# Generated by Django 3.2.18 on 2023-08-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0008_menuitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
