# Generated by Django 3.2.18 on 2023-08-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0012_auto_20230811_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(choices=[('Aurantius (Carrot)', 5.99), ('Chiorus (Avocado)', 6.49), ('Flavus (Paprika)', 5.79), ('Purpureus (Aubergine)', 6.99), ('Roseus (pickled red onion)', 5.89), ('Ruber (Tomato)', 5.59), ('Brunus (all ingredients)', 7.99), ('NC Aurantius (Carrot)', 6.49), ('NC Chiorus (Avocado)', 6.99), ('NC Flavus (Paprika)', 6.49), ('NC Purpureus (Aubergine)', 7.29), ('NC Roseus (pickled red onion)', 6.19), ('NC Ruber (Tomato)', 5.99), ('NC Brunus (all ingredients)', 8.49), ('Nuggets', 3.33), ('Stuffed Potato', 4.99), ('Stuffed Cauliflower', 5.49), ('Stuffed Union garlic', 4.79), ('Stuffed Lentil', 4.99), ('Coriander', 0.99), ('Tomato', 0.49), ('Onion', 0.39), ('Ginger', 0.59), ('Chocolate pie', 4.99), ('Blueberry pie', 5.29), ('Vanilla pie', 4.79), ('Apple pie', 4.49), ('Chocolate Ice-cream', 3.99), ('Strawberry Ice-cream', 3.99), ('Ketchup', 0.29), ('Bearnaise (coco milk)', 0.89), ('Mayonnaise (chickpea)', 0.79), ('Carlic', 0.49), ('Sweat-n-Sour', 0.69), ('Cheese (Tofu)', 1.49), ('Spicy', 0.39), ('French Fries', 2.49), ('Salad', 3.99)], decimal_places=2, max_digits=6),
        ),
    ]
