# Generated by Django 3.2.18 on 2023-08-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0013_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
