# Generated by Django 3.2.18 on 2023-08-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0015_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
