# Generated by Django 3.2.18 on 2023-08-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0019_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(choices=[('Rainbow_Burgers', 'Rainbow_Burgers'), ('No_chicken_Burgers', 'No_chicken_Burgers'), ('No_chicken', 'No_chicken'), ('Wraps', 'Wraps'), ('Wraps_Dressings', 'Wraps_Dressings'), ('Accessories', 'Accessories'), ('Desserts', 'Desserts'), ('Dip', 'Dip'), ('Drinks', 'Drinks'), ('Add_ons', 'Add_ons'), ('Snacks', 'Snacks')], max_length=30),
        ),
    ]
